environment: dev

deployment: 
  metadataName: simple-web-app-deployment
  replicas: 1
  appName: simple-web-app
  containerName: simple-web-app
  image: yeasy/simple-web:latest
  containerPort: 80

service: 
  metadataName: simple-web-app-service
  appName: simple-web-app
  serviceType: NodePort
  port: 80
  targetPort: 80

hpa:
  metadataName: simple-web-app-hpa
  maxReplicas: 3
  utilization: 40