apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadataName }}
spec:
  type: {{ .Values.service.serviceType }}
  selector:
    app: {{ .Values.service.appName }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}